[main]
title = 'Title placeholder'
logo = './logo.png'
notes = true

# Distinct entities that are given their own 
# section with a link
# Format: ['Label', 'Path']
entities = [
['Metadata', './metadata.tsv']
]

# Directories that will be searched
# Format: ['Label', 'Path']
directories = [
['Pipelines', './pipelines'],
['Scripts', './scripts'],
['QIIME2 Exports', './exports'],
['Notebooks', './notebooks']
]

order = [
    'logo', 
    'title', 
    'notes', 
    'Metadata',
    'Scripts',
    'Pipelines',
    'Notebooks',
    'QIIME2 Exports',
]
