name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pandoc
      run: sudo apt-get install -y -qq pandoc
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
