name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y -qq wget
        wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-linux-amd64.tar.gz
        gunzip pandoc-2.10.1-linux-amd64.tar.gz
        tar -xf pandoc-2.10.1-linux-amd64.tar
        sudo cp pandoc-2.10.1/bin/pandoc /usr/bin
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
